### ISSUE TITLE
Exception while resolving variable

### ISSUE THREAD

**Issue by fureunoir** [hypy13/django-daisy#12]
Hey! I've got an exception about missing variable "apps" while rendering admin/index,html first on opening the admin index page, but it disappeared as soon as I modified my DAISY_SETTINGS as follows:

```Python
DAISY_SETTINGS = {
    "SITE_LOGO": "/static/favicon.ico",
    "EXTRA_STYLES": [],
    "EXTRA_SCRIPTS": [],
    "LOAD_FULL_STYLES": True,
    "SHOW_CHANGELIST_FILTER": True,
    "DONT_SUPPORT_ME": False,
    "SIDEBAR_FOOTNOTE": "Coding stuff",
    "APPS_REORDER": {
        "django_celery_beat": {
            "icon": "fa fa-solid fa-timeline",
            "hide": False,
            "app": "django_celery_beat",
            "priority": 0,
            "apps": "",  # added this one here and the exception disappeared
        },
        "django_mailbox": {
            "icon": "fa fa-solid fa-envelope",
            "hide": False,
            "app": "django_mailbox",
            "priority": 1,
            "apps": "",  # added this one here and the exception disappeared
        },
        "geo": {
            "icon": "fa fa-solid fa-globe",
            "hide": False,
            "app": "geo",
            "priority": 2,
            "apps": "",  # added this one here and the exception disappeared
        },
        "payments": {
            "icon": "fa fa-solid fa-wallet",
            "hide": False,
            "app": "payments",
            "priority": 3,
            "apps": "",  # added this one here and the exception disappeared
        },
        "core": {
            "icon": "fa fa-solid fa-house",
            "hide": False,
            "app": "core",
            "priority": 4,
            "apps": "",  # added this one here and the exception disappeared
        },
        "vibes_auth": {
            "icon": "fa fa-solid fa-user",
            "hide": False,
            "app": "vibes_auth",
            "priority": 5,
            "apps": "",  # added this one here and the exception disappeared
        },
    },
}
```

I went further to one model's table and got this:
```log
app  | [2025-01-29 23:27:47 +0000] [44] [DEBUG] GET /en-gb/admin/
app  | 172.18.0.1 - - [29/Jan/2025:23:27:48 +0000] "GET /en-gb/admin/ HTTP/1.0" 200 59868 "https://something.com/en-gb/admin/core/config/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"
app  | [2025-01-29 23:28:06 +0000] [44] [DEBUG] GET /en-gb/admin/core/order/
app  | 2025-01-29 23:28:06 [DEBUG] django.template: Exception while resolving variable 'change_language_url' in template 'admin/change_list.html'.
app  | Traceback (most recent call last):
app  |   File "/root/.cache/pypoetry/virtualenvs/evibes-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/template/base.py", line 883, in _resolve_lookup
app  |     current = current[bit]
app  |               ~~~~~~~^^^^^
app  |   File "/root/.cache/pypoetry/virtualenvs/evibes-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/template/context.py", line 85, in __getitem__
app  |     raise KeyError(key)
app  | KeyError: 'change_language_url'
app  | 
app  | During handling of the above exception, another exception occurred:
app  | 
app  | Traceback (most recent call last):
app  |   File "/root/.cache/pypoetry/virtualenvs/evibes-9TtSrW0h-py3.12/lib/python3.12/site-packages/django/template/base.py", line 889, in _resolve_lookup
app  |     if isinstance(current, BaseContext) and getattr(
app  |                                             ^^^^^^^^
app  | AttributeError: type object 'RequestContext' has no attribute 'change_language_url'
app  | 
app  | During handling of the above exception, another exception occurred: ...
```

Any ideas about fixing it? I've tried to do the same trick but it'd not work 🤒

**Comment by hypy13** [comment]
@fureunoir hi, thanks for reporting issue
may i know which version of django are you using?

**Comment by hypy13** [comment]
actually i did everything, but could'nt get ur error
did u override index.html or override something?

**Comment by fureunoir** [comment]
> actually i did everything, but could'nt get ur error did u override index.html or override something?

Actually I'm working on my opensource project and I could share the whole repo, but I haven't merged it yet. I've overriden for "admin" only django-constance's templates. By the way, I'm using modeltranslation, mptt and other django plugins that'd cause that issue. 

Here's the full project dependencies list:
```toml
[tool.poetry]
name = "eVibes"
version = "1.0.0"
description = "eVibes is an open-source eCommerce backend service built with Django. It’s designed for flexibility, making it ideal for various use cases and learning Django skills. The project is easy to customize, allowing for straightforward editing and extension."
authors = ["fureunoir <contact@fureunoir.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
poetry-core = "^1.9.1"
ruff = "^0.9.2"
six = "1.17.0"
cryptography = "44.0.0"
redis = "^5.2.1"
httpx = "^0.28.1"
celery = { extras = ["flower"], version = "^5.4.0", optional = true }
flower = "^2.0.1"
pillow = "^11.0.0"
south = "^1.0.2"
pygraphviz = { version = "^1.13", optional = true }
requests = "^2.32.3"
gunicorn = "^23.0.0"
psycopg2 = "^2.9.10"
openai =  {version = "^1.51.0", optional = true }
swapper = "^1.4.0"
filetype = "^1.2.0"
colorlog = "^6.9.0"
sentry-sdk = { extras = ["django"], version = "^2.18.0", optional = true }
jupyter = { version = "^1.1.1", optional = true }
django = "5.1.5"
django-extensions = "^3.2.3"
graphene-django = "^3.0.0"
django-redis = "^5.4.0"
django-modeltranslation = "^0.19.12"
django-ratelimit = "^4.1.0"
django-hosts = "^6.0"
django-mptt = "^0.16.0"
django-filter = "^24.2"
django-constance = "^4.1.3"
django-daisy = "1.0.9"
django-mailbox = "^4.10.1"
django-model-utils = "^5.0.0"
django-widget-tweaks = "^1.5.0"
django-cors-headers = "^4.6.0"
django-celery-beat = { version = "^2.6.0", optional = true }
django-json-widget = "^2.0.1"
djangorestframework = "^3.15.2"
djangorestframework-simplejwt = { extras = ["crypto"], version = "^5.3.1" }
djangorestframework-recursive = "^0.1.2"
djangorestframework-camel-case = "^1.4.2"
djangorestframework-xml = "^2.0.0"
drf-spectacular = { extras = ["sidecar"], version = "^0.27.2" }

[tool.poetry.extras]
graph = ["pygraphviz"]
worker = ["celery", "django-celery-beat"]
sentry = ["sentry-sdk"]
AI = ["openai"]
jupyter = ["jupyter"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 88
indent-width = 4

target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

docstring-code-format = false

docstring-code-line-length = "dynamic"
```
